"""initial schema

Revision ID: 2ea78e16f91f
Revises: 
Create Date: 2026-03-08 05:32:31.765345

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea78e16f91f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_sub', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)

    op.create_table('google_calendars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('google_calendar_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_discovered', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('google_calendars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_google_calendars_user_id'), ['user_id'], unique=False)

    op.create_table('google_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encrypted_refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('scopes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('google_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_google_credentials_user_id'), ['user_id'], unique=False)

    op.create_table('icloud_calendars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('caldav_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ctag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_discovered', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('icloud_calendars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_icloud_calendars_user_id'), ['user_id'], unique=False)

    op.create_table('icloud_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('apple_id_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encrypted_app_specific_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('caldav_principal_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('icloud_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_icloud_credentials_user_id'), ['user_id'], unique=False)

    op.create_table('sync_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('icloud_calendar_id', sa.Integer(), nullable=False),
    sa.Column('google_calendar_id', sa.Integer(), nullable=False),
    sa.Column('preferred_side', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['google_calendar_id'], ['google_calendars.id'], ),
    sa.ForeignKeyConstraint(['icloud_calendar_id'], ['icloud_calendars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_pairs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_pairs_user_id'), ['user_id'], unique=False)

    op.create_table('event_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_pair_id', sa.Integer(), nullable=False),
    sa.Column('event_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('google_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('icloud_etag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('google_etag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sync_pair_id'], ['sync_pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_snapshots_sync_pair_id'), ['sync_pair_id'], unique=False)

    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_pair_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('events_created', sa.Integer(), nullable=False),
    sa.Column('events_updated', sa.Integer(), nullable=False),
    sa.Column('events_deleted', sa.Integer(), nullable=False),
    sa.Column('conflicts_resolved', sa.Integer(), nullable=False),
    sa.Column('error_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['sync_pair_id'], ['sync_pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_logs_sync_pair_id'), ['sync_pair_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_logs_sync_pair_id'))

    op.drop_table('sync_logs')
    with op.batch_alter_table('event_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_snapshots_sync_pair_id'))

    op.drop_table('event_snapshots')
    with op.batch_alter_table('sync_pairs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_pairs_user_id'))

    op.drop_table('sync_pairs')
    with op.batch_alter_table('icloud_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_icloud_credentials_user_id'))

    op.drop_table('icloud_credentials')
    with op.batch_alter_table('icloud_calendars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_icloud_calendars_user_id'))

    op.drop_table('icloud_calendars')
    with op.batch_alter_table('google_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_google_credentials_user_id'))

    op.drop_table('google_credentials')
    with op.batch_alter_table('google_calendars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_google_calendars_user_id'))

    op.drop_table('google_calendars')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))

    op.drop_table('users')
    # ### end Alembic commands ###
